### ISSUE TITLE
Crash on wired controller disconnect every time.

### ISSUE THREAD

**Issue by Rygdea** [Ryochan7/DS4Windows#101]
Hey I have a bit of an issue here, this is working fantastically except that if my controller ever disconnects the program crashes with the good old generic windows "ds4windows has stopped working" message.

Testing out a couple of different versions it doesn't happen in Version 1.4.53.

I then searched and it seems to be a very similar to an issue a user had in #3 but that was closed and the build there doesn't work for me.

The Error logs that I get below.

**Event 1000, Application Error**

`Faulting application name: DS4Windows.exe, version: 1.4.87.0, time stamp: 0x597a887f
Faulting module name: KERNELBASE.dll, version: 10.0.15063.483, time stamp: 0xaa6457d1
Exception code: 0xe0434352
Fault offset: 0x0000000000069e08
Faulting process id: 0x35ec
Faulting application start time: 0x01d30daa728cc157
Faulting application path: C:\Program Files\DS4Windows\DS4Windows.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 88328bd0-c09f-49f1-a68b-bbfe2facffb7
Faulting package full name: 
`

**Event 1026, .NET Runtime**

`Application: DS4Windows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   at System.Windows.Forms.Control.Invoke(System.Delegate, System.Object[])
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Send(System.Threading.SendOrPostCallback, System.Object)
   at DS4Windows.DS4Device.performDs4Input()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by Ryochan7** [comment]
I am not entirely sure what is happening based on the report. Normally, I would think that System.UnauthorizedAccessException would happen for a failed I/O operation but the report seems to imply that the final exception occurs in the Form code during an Invoke call. There seems to be only one Form call that occurs when a device is unplugged. There might be a couple sections of code that can be changed to work around whatever is potentially causing the problem. The problem does not happen on my system so I cannot test this problem completely.

**Comment by Ryochan7** [comment]
I have changed the portions of code that I figured could be causing the problem. Without any further details, there is not much that I can do. I will try to get a new test build out soon so you can test the change and see if it helps.

**Comment by Ryochan7** [comment]
Test build

https://drive.google.com/open?id=0B6yGHDx0CFzDUmdLSkZxQ0dyS3c

**Comment by Rygdea** [comment]
Thanks but it still happens man, if helps I am on Win 10 & it does recognize I disconnected as the controller disappears but then instantly hangs forever.

I think these errors match exactly to the point of prob not being very helpful but here they are anyway

```
Faulting application name: DS4Windows.exe, version: 1.4.89.0, time stamp: 0x599e020a
Faulting module name: KERNELBASE.dll, version: 10.0.15063.502, time stamp: 0x005405b5
Exception code: 0xe0434352
Fault offset: 0x0000000000069e08
Faulting process id: 0x2684
Faulting application start time: 0x01d31ca731336012
Faulting application path: C:\Program Files\DS4Windows\DS4Windows.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: f4d4b36f-d533-4bab-a8ec-ec3207e4915a
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Application: DS4Windows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   at System.Windows.Forms.Control.Invoke(System.Delegate, System.Object[])
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Send(System.Threading.SendOrPostCallback, System.Object)
   at DS4Windows.DS4Device.performDs4Input()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```
