### ISSUE TITLE
Load Profile Special Action Crashing DS4Windows

### ISSUE THREAD

**Issue by KenJyn76** [Ryochan7/DS4Windows#1114]
I have a profile that switches profiles to workaround #1109 but it now crashes as of the latest update. I switched the buttons to activate it, at which point it started crashing DS4Windows every time I clicked the keys, I figured it might be a problem with the buttons I chose, but switching it back has not resolved. 

This is all the log shows

2020-02-16 10:33:32.0457|INFO|DS4Windows version 2.0.10
2020-02-16 10:33:32.0537|INFO|Logger created
2020-02-16 10:33:33.2094|INFO|Starting...
2020-02-16 10:33:33.2094|INFO|Connection to ViGEmBus 1.16.112.0 established
2020-02-16 10:33:33.2094|INFO|Searching for controllers...
2020-02-16 10:33:33.2094|INFO|Using Exclusive Mode
2020-02-16 10:34:03.7594|INFO|Found Controller: 00:22:68:FB:60:F7 (BT) (DS4 v.2)
2020-02-16 10:34:03.8308|INFO|Plugging in DS4 Controller for input #1
2020-02-16 10:34:03.8583|INFO|Controller 1 is using Profile "DualShock 4"
2020-02-16 10:34:05.9810|INFO|Controller 1 is using Profile "DualShock 4 X360"
2020-02-16 10:34:06.1289|INFO|Unplugging DS4 Controller for input #1
2020-02-16 10:34:06.1289|INFO|Plugging in X360 Controller for input #1

**Comment by pokemontotalwar** [comment]
Upon further investigation, this seems to happen when the buttons to launch the special action include the PS button. I use the PS button as a modifier for my special actions, so that makes them all crash for me.

**Comment by mika-n** [comment]
Just tested this with the latest V2.0.10 version by creating LoadProfile specAction to load a dualshock4 profile while the default profile was in xbox360 mode. The trigger key was PS+Triangle. 

Worked just fine. The only minor thing is the annoying xbox gaming bar popup icon popping up when PS button is pressed but still the LoadProfile action worked.

There must be something else than just having PS-button as one of the trigger keys to load a profile. Please share the actions.xml file from "%APPDATA%\DS4Windows" settings folder. Or at least the specAction definition of the problematic LoadProfile action.

**Comment by pokemontotalwar** [comment]
> Just tested this with the latest V2.0.10 version by creating LoadProfile specAction to load a dualshock4 profile while the default profile was in xbox360 mode. The trigger key was PS+Triangle.
> 
> Worked just fine. The only minor thing is the annoying xbox gaming bar popup icon popping up when PS button is pressed but still the LoadProfile action worked.
> 
> There must be something else than just having PS-button as one of the trigger keys to load a profile. Please share the actions.xml file from "%APPDATA%\DS4Windows" settings folder. Or at least the specAction definition of the problematic LoadProfile action.

It's so odd, it's working again. I had switched to an UpperTouch trigger key to workaround it for the time being, and, switching back now, it's no longer crashing. Sorry for wasting your time!

**Comment by Ryochan7** [comment]
It might be too late but maybe you should check out the Windows Event Viewer and see if anything is posted there. Look for an Error entry with the source of **.NET Runtime**. Here is an example.

![ds4windows_error_in_event_viewer](https://user-images.githubusercontent.com/581968/74612192-bba42700-50c8-11ea-9e38-f5a2e48e5606.png)

**Comment by pokemontotalwar** [comment]
Yep, .NET Runtime errors. 

Application: DS4Windows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at DS4Windows.ControlService.UnplugOutDev(Int32, DS4Windows.DS4Device, Boolean)
   at DS4Windows.ControlService.On_DS4Removal(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at DS4Windows.DS4Device.performDs4Input()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by pokemontotalwar** [comment]
That got thrown right after an unknown Application error every time I tried to switch profiles this morning

**Comment by pokemontotalwar** [comment]
Would you believe it just happened again. .NET Error log:

Application: DS4Windows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at DS4Windows.ControlService.UnplugOutDev(Int32, DS4Windows.DS4Device, Boolean)
   at DS4Windows.ControlService.On_DS4Removal(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at DS4Windows.DS4Device.performDs4Input()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Ryochan7** [comment]
The error shows that the input controller was being disconnected at the time; maybe Idle Disconnect kicked in at that time. I can only see one place in that routine where something could go wrong but it would be rare. I can only assume two threads were trying to unplug an output device around the same time (input thread and main thread) as that should be the only way it happens.

**Comment by pokemontotalwar** [comment]
> The error shows that the input controller was being disconnected at the time; maybe Idle Disconnect kicked in at that time. I can only see one place in that routine where something could go wrong but it would be rare. I can only assume two threads were trying to unplug an output device around the same time (input thread and main thread) as that should be the only way it happens.

I can't imagine it would be idle disconnecting, after the crash I'd restart the program and immediately use the action again and it would crash with the same error. My only idea is that it would be because I have it on the same keybind to switch to the X360 layout and to switch back, and it registers as two instantaneous clicks, so tries to disconnect and reconnect twice at once.

That theory seems flawed, though, since my workaround is to just swap them both to an Upper Touch function, so it should crash the same way if that's the issue

**Comment by mika-n** [comment]
I tested LoadProfile with PS+Options (between xbox and ds4 profiles) key combination and tried to torment the key combination as much as possible (repeated presses several times etc...). Didn't crash. Something very rare must have happen in your environment at the same time (idle disconnect, BT disconnection hiccups)? Or do you use auto-profile feature at the same time you use specific specAction key combination to load adhoc profiles?

**Comment by pokemontotalwar** [comment]
> I tested LoadProfile with PS+Options (between xbox and ds4 profiles) key combination and tried to torment the key combination as much as possible (repeated presses several times etc...). Didn't crash. Something very rare must have happen in your environment at the same time (idle disconnect, BT disconnection hiccups)? Or do you use auto-profile feature at the same time you use specific specAction key combination to load adhoc profiles?

Nope, I don't have any auto-profiles set up. It's all very odd. I've changed my specActions around to make hitting Share change my profile and my PS button does a few different things now, so it's fine on my end. I'd hate for anybody else to run into this, though, so I'm willing to help test anything you guys need.
