### ISSUE TITLE
DS4Windows does not start

### ISSUE THREAD

**Issue by csantoni** [Ryochan7/DS4Windows#1284]
Last night Windows 10 updated and DS4Windows no longer starts. Updates installed were 2020-05 Cumulative Update for .Net Framework 3.5 and 4.8 for Windows 10 Version 1090 for x64 (KB4552931) and 2020-05 Cumulative Update for Windows 10 Version 1909 for x64-based Systems (KB4556799).

When trying to launch DS4Windows, nothing happens. Event Viewer logs the following errors:

`Application: DS4Windows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlLoader.Load(System.Xml.XmlDocument, System.Xml.XmlReader, Boolean)
   at System.Xml.XmlDocument.Load(System.Xml.XmlReader)
   at System.Xml.XmlDocument.Load(System.String)
   at DS4Windows.BackingStore.LoadLinkedProfiles()
   at DS4WinWPF.App.Application_Startup(System.Object, System.Windows.StartupEventArgs)
   at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at DS4WinWPF.App.Main()
`

`Faulting application name: DS4Windows.exe, version: 2.1.0.0, time stamp: 0xefce1f63
Faulting module name: KERNELBASE.dll, version: 10.0.18362.815, time stamp: 0xb89efff3
Exception code: 0xe0434352
Fault offset: 0x000000000003a799
Faulting process id: 0x2b3c
Faulting application start time: 0x01d62a47cfd367f1
Faulting application path: C:\Users\csantoni\DS4Windows\DS4Windows.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: cea18998-b8af-4552-9a1e-d154921d266e
Faulting package full name: 
Faulting package-relative application ID: `

I have tried deleting Profiles.xml and re-downloading DS4Windows and multiple reboots. Nothing helps.

**Comment by csantoni** [comment]
Must have been some kind of xml corruption. Deleted xml in AppData directory and started working again.

**Comment by Ryochan7** [comment]
It looks like DS4Windows crashed while attempting to load the LinkedProfiles.xml file. The traceback shows that DS4Windows found the file but the XmlDocument.Load method threw an XmlException while parsing the XML. I'm guessing the file got corrupted somehow.
