### ISSUE TITLE
Crash When Selecting Controller to DS4

### ISSUE THREAD

**Issue by hadyanq1** [Ryochan7/DS4Windows#1296]
Hi everyone, first of all thank you for your great work with this tool.
My issue is I never able to select controller to DS4, the app crashes and it prevents me from selecting it back to X360.

I tried erasing the profile, it works for a while, then crash again after selecting DS4 as the controller type. Looking through the log didn't reaveal anything obvious, so I downloaded the debug version and it returned this stack trace:

```
2020-05-23 11:38:19.1807|INFO|DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#acpi0011#3&25a41f9f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant wireless radio controls  VID=0x0000  PID=0x0000  Usage=0xC  Version=0x0
2020-05-23 11:38:19.1807|INFO|DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#cust0001&col01#5&29f77e77&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant mouse  VID=0x06CB  PID=0xCDAA  Usage=0x2  Version=0x103
2020-05-23 11:38:19.1807|INFO|DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#cust0001&col02#5&29f77e77&1&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant touch pad  VID=0x06CB  PID=0xCDAA  Usage=0x5  Version=0x103
2020-05-23 11:38:19.1807|INFO|DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#cust0001&col03#5&29f77e77&1&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Microsoft Input Configuration Device  VID=0x06CB  PID=0xCDAA  Usage=0xE  Version=0x103
2020-05-23 11:38:19.1807|INFO|DEBUG: EnumerateDS4. HID#5 Path=\\?\hid#cust0001&col04#5&29f77e77&1&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x06CB  PID=0xCDAA  Usage=0x1  Version=0x103
2020-05-23 11:38:19.1807|INFO|DEBUG: EnumerateDS4. HID#6 Path=\\?\hid#vid_045e&pid_028e&ig_00#3&14107a10&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x045E  PID=0x028E  Usage=0x5  Version=0x0
2020-05-23 11:38:19.1807|INFO|DEBUG: EnumerateDS4. HID#7 Path=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&05c4#8&dd0b64c&2&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x054C  PID=0x05C4  Usage=0x5  Version=0x0
2020-05-23 11:38:19.1807|INFO|DEBUG: EnumerateDS4. HID#7 detected as DS4 compatible gamepad device
2020-05-23 11:38:19.1807|INFO|DEBUG: IsRealDS4. IsRealDS4=True  hDevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&05c4#8&dd0b64c&2&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  deviceInstanceID=hid\{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&05c4\8&dd0b64c&2&0000  Device_UINumber=
2020-05-23 11:38:19.1807|INFO|DEBUG: findControllers. Found 1 possible device
2020-05-23 11:38:19.1807|INFO|DEBUG: findControllers. Idx=0 Potential DS4 gamepad. Description=HID-compliant game controller  Path=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&05c4#8&dd0b64c&2&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
2020-05-23 11:38:29.3034|ERROR|Thread Crashed with message Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
2020-05-23 11:38:29.3191|ERROR|System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at DS4WinWPF.DS4Forms.MainWindow.ProfEditSBtn_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at Xceed.Wpf.Toolkit.DropDownButton.OnClick()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2020-05-23 11:38:29.3191|ERROR|Thread Crashed with message Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
2020-05-23 11:38:29.3191|ERROR|System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at DS4WinWPF.DS4Forms.MainWindow.ProfEditSBtn_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at Xceed.Wpf.Toolkit.DropDownButton.OnClick()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DS4WinWPF.App.Main()
2020-05-23 11:38:29.3191|INFO|Stopping X360 Controllers
2020-05-23 11:38:29.3191|INFO|Closing connection to ViGEmBus
2020-05-23 11:38:29.3191|INFO|DEBUG: performDs4Input. BT ReadWithFileStream failed. ErrorCode=ReadError WinError=997
2020-05-23 11:38:29.3191|INFO|Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode=6
2020-05-23 11:38:29.3191|INFO|DEBUG: sendOutputReport. ERROR. writeOutput failed. Force quiting output thread. LastErrorCode=6
2020-05-23 11:38:29.3191|INFO|Unplugging X360 Controller for input #1
2020-05-23 11:38:29.3191|INFO|Controller 1 was removed or lost connection
2020-05-23 11:38:29.3816|INFO|Stopping DS4 Controllers
2020-05-23 11:38:29.3816|INFO|Stopped DS4Windows
```

My controller is genuine DS4, built from the older model (no lightbar on top) if it's relevant. Could please let me know if there's anything that can be done from my end? Thank you.

**Comment by hadyanq1** [comment]
Edit: solved it after deleting the whole DS4 folder and running freshly downloaded zip.
