### ISSUE TITLE
System.AggregateException Error after update to 3.0.1

### ISSUE THREAD

**Issue by Eruasa** [Ryochan7/DS4Windows#2050]
I got this error after I updated DS4Windows. It happens when I connect my PS4 controller to my PC via a USB cable.
I tried to delete the DS4Windows,deps.json, DS4Windows.runtimeconfig.json, HidGuardhelper.deps.json and the HidGuardhelper.runtimeconfig.json files to force it to update, but the error occurred again.

System.AggregateException: One or more errors occurred. ('.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.)
 ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at DS4Windows.ProfileMigration..ctor(String filePath)
   at DS4Windows.BackingStore.LoadProfile(Int32 device, Boolean launchprogram, ControlService control, String propath, Boolean xinputChange, Boolean postLoad)
   at DS4Windows.Global.LoadProfile(Int32 device, Boolean launchprogram, ControlService control, Boolean xinputChange, Boolean postLoad)
   at DS4Windows.ControlService.HotPlug()
   at DS4WinWPF.DS4Forms.MainWindow.InnerHotplug2()
   at DS4WinWPF.DS4Forms.MainWindow.<WndProc>b__86_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

**Comment by Masamune3210** [comment]
Please fill out the issue template instead of just deleting it and making one long paragraph

**Comment by Ryochan7** [comment]
Whatever profile was attempting to be loaded is corrupt. Other than adding some extra exception handling at that point, there is nothing else to do on my end.
