### ISSUE TITLE
DS4Windows fails to update since the release of version 3.0.2

### ISSUE THREAD

**Issue by Newtype14** [Ryochan7/DS4Windows#2072]
When I had version 3.0.1 installed, I got a message saying there was a new update. I clicked the "update" button as usual, but the program crashed while it was installing (without any error message). I couldn't even start DS4Windows anymore because the .exe got deleted from the program folder. I ended up having to to do a clean installation.

Now, with version 3.0.2 installed, I got a message saying that 3.0.3 was out. I clicked the "update" button and the exact same thing happened. I'm forced to do a clean install again. I never had any issues updating prior to version 3.0.2.

OS: Windows 10 LTSC version 1809 build 17763.1879
.NET 5 (x64) installed.

Latest log before the update attempt to 3.0.3:
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6322020/ds4windows_log.txt)

**Comment by Malumen** [comment]
Same: startup action to request download and install of new version works OK, it just seems to fail after downloading the update... I can find the update folder with 3.0.3 in the `AppData` folder just fine, and then extract it. Unfortunately after overwriting it with the new version, it does not run at startup and also does not seem to remember if I tell it to use %AppData% or Program folder...

Is there a particular place we should be extracting and installing the DS4Windows program to? I just have mine in my documents folder...

**Comment by Hackerpunk1** [comment]
I have my DS4Windows in the following location: "D:\Downloads\Drivers\DS4\DS4Windows"
After every update since 3.0.2, the files gets extracted to "D:\Downloads\Drivers\DS4\DS4Windows\Update Files\DS4Windows"
Which inturns create issues to launch the app from task schedule and so on.
@Ryochan7 Please do check the update script and thanks a lot for your time and dedication to the project

**Comment by Ryochan7** [comment]
> After every update since 3.0.1, the files gets extracted to "D:\Downloads\Drivers\DS4\DS4Windows\Update Files\DS4Windows"
Which inturns create issues to launch the app from task schedule and so on.

Iit has been that way since the Jays2Kings days. That is the temporary location that the DS4Windows archive is extracted to before files are moved to the main program folder. That folder is removed once DS4Updater is finished.

As for the original issue, the log shows DS4Windows shut down cleanly. The issue has to be within the DS4Updater.exe app itself. There is no logging implemented there so you would have to open the Windows Event Viewer to see the .NET Runtime error; I don't have my Windows machine on right now so I cannot post the path from the Control Panel (its in Administration Tools somewhere).

The updater has still worked fine for me even on my Windows 7 VM.

**Comment by Newtype14** [comment]
Got it: [NET Runtime Error.txt](https://github.com/Ryochan7/DS4Windows/files/6328129/NET.Runtime.Error.txt)

**Comment by jernejs** [comment]
I have the same problem - DS4Updater crashes leaving me with non-functional DS4Windows:
```
Application: DS4Updater.exe
CoreCLR Version: 5.0.521.16609
.NET Version: 5.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException: Access to the path 'W:\Games\Helpers\DS4Windows\UtilLibrary.dll' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Updater2.MainWindow.wc_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Net.WebClient.<StartAsyncOperation>b__78_4(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Updater2.App.Main()
```

**Comment by Masamune3210** [comment]
Make sure you have full read write permission for the folder the program is in, and make sure the folder isn't read only

**Comment by Newtype14** [comment]
Going from 3.0.3 to 3.0.4 worked for me. I didn't have to do anything.

**Comment by jernejs** [comment]
I have full permission in the folder - I think the problem is that DS4Updater is trying to replace the files while HidGuardHelper.exe is still running (that's the process that has UtilLibrary.dll loaded).

**Comment by Masamune3210** [comment]
Yeajh, that would do it too

**Comment by Ryochan7** [comment]
Didn't think of that issue; luckily it has never happened to me. HidGuardHelper only checks for DS4Windows once a second and will then close if the process is no longer running. Might want to add an extra delay to the Updater.

This is not a problem when using HidHide.

**Comment by Ryochan7** [comment]
The underlying issue should have been address in DS4Updater 1.5.4. That app was bundled with DS4Windows 3.0.6. Checking for updates in DS4Windows should pull the latest DS4Updater exe before attempting to update the main DS4Windows app.
