### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by JupiterSky11** [Ryochan7/DS4Windows#2277]
Unsure if this is wine, or this program, or something else, but I can't run the program.  Crashes after a bunch of probably unrelated warnings.

```
System.TypeInitializationException: The type initializer for 'Microsoft.Win32.TaskScheduler.TaskService' threw an exception.
 ---> System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.Win32.TaskScheduler.V2Interop.ITaskService.get_ConnectedUser()
   at Microsoft.Win32.TaskScheduler.TaskService.Connect()
   at Microsoft.Win32.TaskScheduler.TaskService..ctor()
   at Microsoft.Win32.TaskScheduler.TaskService.get_Instance()
   at Microsoft.Win32.TaskScheduler.TaskService..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Win32.TaskScheduler.TaskService.GetLibraryVersionFromLocalOS()
   at Microsoft.Win32.TaskScheduler.TaskService.ResetHighestSupportedVersion()
   at Microsoft.Win32.TaskScheduler.TaskService..ctor()
   at DS4WinWPF.StartupMethods.HasTaskEntry()
   at DS4WinWPF.DS4Forms.ViewModels.SettingsViewModel..ctor()
   at DS4WinWPF.DS4Forms.MainWindow..ctor(ArgumentParser parser)
   at DS4WinWPF.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at DS4WinWPF.App.Main()
0188:fixme:advapi:RegisterEventSourceW ((null),L".NET Runtime"): stub
0188:fixme:advapi:ReportEventW (00000000CAFE4242,0x0001,0x0000,0x00000402,0000000000000000,0x0001,0x00000000,000000000019BA90,0000000000000000): stub
0188:err:eventlog:ReportEventW L"Application: DS4Windows.exe\nCoreCLR Version: 5.0.721.25508\n.NET Version: 5.0.7\nDescription: The process was terminated due to an unhandled exception.\nException Info: System.TypeInitializationException: The type initializer for 'Microsoft.Win32.TaskScheduler.TaskService' threw an excep"...
0188:fixme:advapi:DeregisterEventSource (00000000CAFE4242) stub
wine: Unhandled exception 0xe0434352 in thread 188 at address 000000007B0122DE (thread 0188), starting debugger...
Unhandled exception: 0xe0434352 in 64-bit code (0x000000007b0122de).
```

**Comment by Masamune3210** [comment]
Considering its whining about the Task Scheduler not being implemented, its wine

**Comment by Ryochan7** [comment]
I miss when people actually cared about **native** Linux apps. Now people just want Linux to be an even worse version of Windows with all traces of software freedom removed. I don't like the guy but rms was right about Wine

![linux_cucks_wallpaper](https://user-images.githubusercontent.com/581968/124814544-c06eb280-df2b-11eb-95d0-0df82eba80d6.png)

**Comment by JupiterSky11** [comment]
Hey, I just use Wine as a bandaid.  Where there's no native support, there's Wine.  It's not like I want to, but it's also not like you and other app developers can invest the time in re-writing their entire projects to be Linux friendly, so Wine serves its purpose.

**Comment by mika-n** [comment]
@JupiterSky11 If you have VisualStudio then you can try to compile the latest DS4Windows app yourself. Try to add "System.TypeInitializationException" catch exception in SettingsViewModel.cs::SettingsViewModel constructor when it calls StartupMethods.HasTaskEntry() code line. Or somehow identify if the system is running under WINE and then skipping HasTaskEntry logic.

Anyway, could be that there are numerous other non-implemented calls in WINE .NET Core, so it is up to those users using WINE to test and tweak it. It is next to impossible to test it if devs don't use WINE environment so feel free try test it yourself.
