### ISSUE TITLE
Keyboard & Mouse Feature crashing DS4 if more than 6 keys are being used.

### ISSUE THREAD

**Issue by RegretfulGit** [Ryochan7/DS4Windows#2298]
**Describe the bug**
When using the Keyboard and Mouse feature If a total of 6 key are being pressed at a time and it exceeds this amount (7) DS4 will freeze/hang if another button is pressed What will then happen is the last key pressed act as if it being held down and causing it to spam that key (I.E QQQQQQQQQQQQQQQ)

And the only way to fix it is by rebooting.  Killing it in task manager does not stop the issue.  Please let me know if I can provide any more info that would help!

1. Create keyboard and mouse profile
2. Assign keyboard buttons to controller
3. Hold down 6 buttons that would activate 6 key (for me that was R,B,Q, N,G.H, which maps to R1, R2, L1, L2, Triangle, Circle,)
4. Press any extra button while holding down the other buttons
5. DS4 will hang/crash causing that latest button to remain active/held down (QQQQQQQQQQQQQQQ)
**Expected behavior**
For DS4 to not crash due to higher amount of keys being used.

**Screenshots and Logs**
Error shown in logs:

2021-07-11 01:19:51.7938|ERROR|Thread App Crashed with message Index was outside the bounds of the array.
2021-07-11 01:19:51.8142|ERROR|System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FakerInputWrapper.KeyboardReport.GetRawKeyCodes()
   at FakerInputWrapper.FakerInput.UpdateKeyboard(KeyboardReport report)
   at DS4Windows.DS4Control.FakerInputHandler.Sync()
   at DS4Windows.Mapping.Commit(Int32 device)
   at DS4Windows.ControlService.On_Report(DS4Device device, EventArgs e, Int32 ind)
   at DS4Windows.DS4Device.performDs4Input()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ThreadHelper.ThreadStart()
2021-07-11 01:19:51.8142|INFO|Stopping Virtual Output Controllers
2021-07-11 01:19:51.8142|INFO|Closing connection to ViGEmBus
2021-07-11 01:19:51.8699|INFO|Stopping DS4 Input Controllers
2021-07-11 01:19:51.8699|INFO|Stopped DS4Windows
2021-07-11 01:20:47.6948|INFO|User Session Ending
[ds4windows_log_20210711.4.txt](https://github.com/Ryochan7/DS4Windows/files/6796424/ds4windows_log_20210711.4.txt)

**Desktop (please complete the following information):**
Windows 10 Pro
Original PS4 Controller

**Comment by Ryochan7** [comment]
Using that many keys at once is not even possible with most, if not any, physical keyboards; the HID report description for my keyboard says that only 6 active keys are supported . Why try to map something like this? The crash is the only valid portion of this issue.

**Comment by pcrov** [comment]
> Using that many keys at once is not even possible with most, if not any, physical keyboards;

Many keyboards support greater than 6-key rollover. For some examples search your favorite keyboard retailer for "nkro."

**Comment by Ryochan7** [comment]
Found the problem. It was an old bug carried over the VMultiDLLWrapper project.

https://github.com/simphax/VMultiDll/blob/master/VMultiDllWrapper/KeyboardReport.cs#L180

**Comment by Ryochan7** [comment]
Need to get a new version of DS4Windows out sometime
