### ISSUE TITLE
DS4Windows.exe not working

### ISSUE THREAD

**Issue by Monstarrrr** [Ryochan7/DS4Windows#2443]
**Describe the bug**
Running _**DS4Windows.exe**_ does nothing,  
I tried: 
- Running as administrator
- Restarting PC

**Desktop (please complete the following information):**
 - Windows 10 Pro 64-bit
 - DS4Windows v3.0.18

**Comment by Ryochan7** [comment]
There are a couple of different resources that might help. Is a log file generated (located in the Logs folder)? If DS4Windows did not generate a log file, you might want to check out the Windows Event Viewer (Control Panel > System and Security > Administrative Tools > Event Viewer) and check the Application Logs for a .NET Runtime error entry.

**Comment by rodrigotm** [comment]
I have same problem here, the program dont open, folling error on Appliction Logs from windows:

Nome do Log:   Application
Fonte:         .NET Runtime
Data:          03/07/2022 16:32:30
Identificação do Evento:1026
Categoria da Tarefa:Nenhum
Nível:         Erro
Palavras-chave:Clássico
Usuário:       N/D
Computador:    DESKTOP-4CJKBRF
Descrição:
Application: DS4Windows.exe
CoreCLR Version: 5.0.1722.21314
.NET Version: 5.0.17
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'FakerInputDll.dll' or one of its dependencies: Não foi possível encontrar o módulo especificado. (0x8007007E)
   at FakerInputWrapper.FakerInput.fakerinput_alloc()
   at FakerInputWrapper.FakerInput..ctor()
   at DS4Windows.DS4Control.FakerInputHandler..ctor()
   at DS4Windows.DS4Control.VirtualKBMFactory.DetermineHandler(String identifier)
   at DS4Windows.Global.InitOutputKBMHandler(String identifier)
   at DS4Windows.ControlService.InitOutputKBMHandler()
   at DS4Windows.ControlService..ctor(ArgumentParser cmdParser)
   at DS4WinWPF.App.<>c__DisplayClass32_0.<CreateControlService>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

XML de Evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-07-03T19:32:30.0143175Z" />
    <EventRecordID>1937</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-4CJKBRF</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: DS4Windows.exe
CoreCLR Version: 5.0.1722.21314
.NET Version: 5.0.17
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'FakerInputDll.dll' or one of its dependencies: Não foi possível encontrar o módulo especificado. (0x8007007E)
   at FakerInputWrapper.FakerInput.fakerinput_alloc()
   at FakerInputWrapper.FakerInput..ctor()
   at DS4Windows.DS4Control.FakerInputHandler..ctor()
   at DS4Windows.DS4Control.VirtualKBMFactory.DetermineHandler(String identifier)
   at DS4Windows.Global.InitOutputKBMHandler(String identifier)
   at DS4Windows.ControlService.InitOutputKBMHandler()
   at DS4Windows.ControlService..ctor(ArgumentParser cmdParser)
   at DS4WinWPF.App.&lt;&gt;c__DisplayClass32_0.&lt;CreateControlService&gt;b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
</Data>
  </EventData>
</Event>

**Comment by rodrigotm** [comment]
Nome do Log:   Application
Fonte:         Application Error
Data:          03/07/2022 16:32:30
Identificação do Evento:1000
Categoria da Tarefa:(100)
Nível:         Erro
Palavras-chave:Clássico
Usuário:       N/D
Computador:    DESKTOP-4CJKBRF
Descrição:
Nome do aplicativo com falha: DS4Windows.exe, versão: 3.0.18.0, carimbo de data/hora: 0x60c8ffcd
Nome do módulo com falha: KERNELBASE.dll, versão: 10.0.19041.1741, carimbo de data/hora: 0xe9b4a91b
Código de exceção: 0xe0434352
Deslocamento da falha: 0x0000000000034fd9
ID do processo com falha: 0x3bc0
Hora de início do aplicativo com falha: 0x01d88f13a20fbc8f
Caminho do aplicativo com falha: C:\Users\rodri\Downloads\DS4Windows_3.0.18_x64 (1)\DS4Windows\DS4Windows.exe
Caminho do módulo com falha: C:\Windows\System32\KERNELBASE.dll
ID do Relatório: 53eb1776-b2b4-49aa-af7f-4f69b2269854
Nome completo do pacote com falha: 
ID do aplicativo relativo ao pacote com falha: 
XML de Evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-07-03T19:32:30.5279883Z" />
    <EventRecordID>1938</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-4CJKBRF</Computer>
    <Security />
  </System>
  <EventData>
    <Data>DS4Windows.exe</Data>
    <Data>3.0.18.0</Data>
    <Data>60c8ffcd</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.1741</Data>
    <Data>e9b4a91b</Data>
    <Data>e0434352</Data>
    <Data>0000000000034fd9</Data>
    <Data>3bc0</Data>
    <Data>01d88f13a20fbc8f</Data>
    <Data>C:\Users\rodri\Downloads\DS4Windows_3.0.18_x64 (1)\DS4Windows\DS4Windows.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>53eb1776-b2b4-49aa-af7f-4f69b2269854</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by Ryochan7** [comment]
> Exception Info: System.DllNotFoundException: Unable to load DLL 'FakerInputDll.dll' or one of its dependencies: Não foi possível encontrar o módulo especificado. (0x8007007E)

The DS4Windows install is incomplete. It looks like you are missing a required linked DLL. Just checked the GitHub archive and FakerInputDll.dll is bundled

**Comment by Ryochan7** [comment]
Nothing to do here. Closing
