### ISSUE TITLE
Does not start for .NET Framework 4.0 in Windows 11

### ISSUE THREAD

**Issue by gsoler** [Ryochan7/DS4Windows#2556]
**Describe the bug**
I have followed all instructions in your website to install DS4Windows and all dependencies but does not start. When I see the log, it shows the following error:

`2022-09-02 11:22:13.1928|ERROR|Thread Crashed with message Could not find an installation of .NET Framework v4.0.30319. System.Management requires native modules from the .NET Framework to operate.
2022-09-02 11:22:13.1928|ERROR|System.PlatformNotSupportedException: Could not find an installation of .NET Framework v4.0.30319. System.Management requires native modules from the .NET Framework to operate.
   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementScope.Connect()
   at DS4WinWPF.DS4Forms.MainWindow.SetupEvents()
   at DS4WinWPF.DS4Forms.MainWindow..ctor(ArgumentParser parser)
   at DS4WinWPF.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at DS4WinWPF.App.Main()`

When I try to install .NET Framework 4.0, it says that the operating systems has it by default and can't install.

**To Reproduce**
Install the application and try to start in Windows 11.
Select any option to save data.

**Expected behavior**
Application starts normally.

**Screenshots and Logs**
I have no screenshots, because it does not do anything. The logs are in description.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 11 Pro 22000.856
 - DS4Windows Version 3.1.4

**Comment by Ryochan7** [comment]
Looks like the System.Management assembly is considered deprecated and it does require a .NET Framework install in order to work. That is not wanted. The suggested replacement assembly is Microsoft.Management.Infrastructure. Not sure if that would work out and System.Management has been updated more recently than Microsoft.Management.Infrastructure.

I really hate Microsoft.

https://www.nuget.org/packages/Microsoft.Management.Infrastructure/

Also, hopefully you are running the x64 package as you might have more problems if you try to run the x86 version. I would be willing to just outright remove suspend support to get rid of the dependency entirely at this point. Cannot test the feature completely on my PC anyway and it seems to present nothing but problems.

Related issues:
[https://github.com/dotnet/runtime/issues/66386](https://github.com/dotnet/runtime/issues/66386)
[https://github.com/dotnet/runtime/issues/45143](https://github.com/dotnet/runtime/issues/45143)

**Comment by Ryochan7** [comment]
Funny how this was a deliberate design decision going all the way back to .NET Core. Also, introduce new tech and deprecate old tech. Don't give any migration path to incorporate an existing feature.

**Comment by Ryochan7** [comment]
Might be relevant for this

https://stackoverflow.com/a/65129930
https://www.activexperts.com/admin/scripts/wmi/vbscript/0352/
https://gist.github.com/shoddyguard/0edb7b34e1c8c91a409d8c28c2e8c632
