### ISSUE TITLE
Error after 3.1.5 update

### ISSUE THREAD

**Issue by xinxs** [Ryochan7/DS4Windows#2598]
I'm having this issue after the last update. I use windows 11.

09/22/2022 20:10:33: Could not load file or assembly 'Nefarius.Utilities.DeviceManagement, Version=3.0.165.0, Culture=neutral, PublicKeyToken=null'. O sistema não pode encontrar o arquivo especificado.
09/22/2022 20:10:40: System.AggregateException: One or more errors occurred. (Could not load file or assembly 'Nefarius.Utilities.DeviceManagement, Version=3.0.165.0, Culture=neutral, PublicKeyToken=null'. O sistema não pode encontrar o arquivo especificado.)
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Nefarius.Utilities.DeviceManagement, Version=3.0.165.0, Culture=neutral, PublicKeyToken=null'. O sistema não pode encontrar o arquivo especificado.
File name: 'Nefarius.Utilities.DeviceManagement, Version=3.0.165.0, Culture=neutral, PublicKeyToken=null'
   at DS4Windows.DS4Devices.findControllers()
   at DS4Windows.ControlService.<>c.<HotPlug>b__111_0()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location ---
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at DS4Windows.ControlService.HotPlug()
   at DS4WinWPF.DS4Forms.MainWindow.InnerHotplug2()
   at DS4WinWPF.DS4Forms.MainWindow.<WndProc>b__84_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

**Comment by Kanuan** [comment]
There is a file in the v3.1.5 folder called `DS4Windows.deps.json`. It is missing the references to the `Nefarius.Utilities.DeviceManagement`, resulting in a error.

For those wanting a duct tape fix while a new version with this issue fixed is not released:

1. Download: [DS4Windows.deps.zip](https://github.com/Ryochan7/DS4Windows/files/9629938/DS4Windows.deps.zip)
    - This is just the archived file that is generated when compiling the project from the source code (master branch, x64 build)
    - This is only for the x64 build 
1. Extract the archive
1. Replace the `DS4Windows.deps.json`  inside the v3.1.5 folder with the one you downloaded and extracted

It's just a .json file. You can open it with the notepad to compare in case there is anything malicious.

**Comment by xinxs** [comment]
Working great now, thanks

**Comment by drip2broke** [comment]
so is there any way you can type out a step by step on how to fix the error because im getting the same error for my ps5 controller and i dont know how to change the json thing and extract it and stuff?

**Comment by raff-run** [comment]
> so is there any way you can type out a step by step on how to fix the error because im getting the same error for my ps5 controller and i dont know how to change the json thing and extract it and stuff?

A more detailed explanation:

1. Install the x64 version of ds4windows, in case you don't have it: https://docs.ds4windows.app/guides/install-setup/, this fix won't work for the x86 version
2. Download the file Kanuan linked: https://github.com/Ryochan7/DS4Windows/files/9629938/DS4Windows.deps.zip
3. Go to the folder where DS4Windows is installed (where the .exe is)
4. Move the file downloaded in step 2 to the same folder:
![image](https://user-images.githubusercontent.com/44688128/191874436-8d9ca81b-8a90-457f-ab7d-eff0fb2b3be4.png)
5. Open the .zip and move/copy the file inside to the same folder the .exe is:
![image](https://user-images.githubusercontent.com/44688128/191874533-2971f006-b856-42ba-b5f1-69b1798c48b8.png)
6. Windows will say the folder already has that file, click to replace/overwrite:
![image](https://user-images.githubusercontent.com/44688128/191874571-50477e08-3409-4f21-89d3-a1ec7ed67e5e.png)
7. Done!

**Comment by Ryochan7** [comment]
Will get a hotfix out shortly

**Comment by rkennedy1** [comment]
Thanks for the duct tape fix :) saved my gaming night
