### ISSUE TITLE
DS4Windows is crashing/closing itself when playing games

### ISSUE THREAD

**Issue by CarissaIsWierd** [Ryochan7/DS4Windows#2623]
**Describe the bug**
In the log it says "Thread Crashed with message UpdateToolTip failed".

**Screenshots and Logs**
[ds4windows_log_20221003.2.txt](https://github.com/Ryochan7/DS4Windows/files/9697327/ds4windows_log_20221003.2.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense (CFI-ZCT1W)
 - OS: Windows 10 Pro Build 2004
 - DS4Windows Version 3.1.6

**Additional context**
It never did this with 3.0.10 (which I'd been using until recently.)

**Comment by Strato83** [comment]
Hi. Having the same issue on version 3.1.4, Win11Pro 21H2.

**Comment by Ryochan7** [comment]
I encountered this myself a couple days ago while charging my DualSense. The function fails in the SendMessage call made by H.NotifyIcon. Looked it over and the only reason I could conclude for why it might be happening is that the call should have probably been made from the main GUI thread rather than the controller input thread. Got that enforced now and didn't run into the problem the couple times I have charged my DualSense since then.

**Comment by Strato83** [comment]
Still have this issue on version 3.1.7.
Both crashes on 3.1.7 got happened right after PC wakes up from sleep mode. Without any controllers connected.
Logs:
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/9910031/ds4windows_log.txt)

[ds4windows_log_20221026.0.txt](https://github.com/Ryochan7/DS4Windows/files/9910038/ds4windows_log_20221026.0.txt)

**Comment by CarissaIsWierd** [comment]
Yeah, even on 3.1.9 it was closing itself all the time, so I gave up and went back to 3.0.10 :/

**Comment by Kubusky** [comment]
Same issue here,
Dualsense with Win 11 Pro 22H2, DS4Windows 3.1.10 - app crash on resume from sleep, need to launch again manually. 
Trying to setup task in task scheduler to open DS4Windows on resume from sleep as a workaround for now..

```
--sleep resume log--
2022-11-15 10:27:16.8246|INFO|Starting...
2022-11-15 10:27:16.8246|INFO|Using output KB+M handler: SendInput
2022-11-15 10:27:16.8246|INFO|Connection to ViGEmBus 1.21.442.0 established
2022-11-15 10:27:16.8246|INFO|Searching for controllers...
2022-11-15 10:27:16.8246|INFO|Using Shared Mode
2022-11-15 10:27:16.8670|ERROR|Thread Crashed with message UpdateToolTip failed.
2022-11-15 10:27:16.8842|ERROR|System.InvalidOperationException: UpdateToolTip failed.
   at H.NotifyIcon.Core.TrayIcon.UpdateToolTip(String text) in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 365
   at H.NotifyIcon.TaskbarIcon.WriteToolTipSettings() in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.ToolTips.cs:line 194
   at H.NotifyIcon.TaskbarIcon.OnToolTipTextChanged(String oldValue, String newValue) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.ToolTips.cs:line 43
   at H.NotifyIcon.TaskbarIcon.<>c.<.cctor>b__222_5(DependencyObject sender, DependencyPropertyChangedEventArgs args) in /_/src/libs/H.NotifyIcon.Wpf/DependencyPropertyGenerator/H.Generators.DependencyPropertyGenerator/TaskbarIcon.Properties.ToolTipText.generated.cs:line 22
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at MS.Internal.Data.ValueChangedEventManager.ValueChangedRecord.OnValueChanged(Object sender, EventArgs e)
   at DS4WinWPF.DS4Forms.ViewModels.TrayIconViewModel.set_TooltipText(String value)
   at DS4WinWPF.DS4Forms.ViewModels.TrayIconViewModel.PopulateToolText()
   at DS4WinWPF.DS4Forms.ViewModels.TrayIconViewModel.<StartPopulateText>b__59_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2022-11-15 10:27:16.8842|ERROR|Thread Crashed with message UpdateToolTip failed.
2022-11-15 10:27:16.8842|ERROR|System.InvalidOperationException: UpdateToolTip failed.
   at H.NotifyIcon.Core.TrayIcon.UpdateToolTip(String text) in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 365
   at H.NotifyIcon.TaskbarIcon.WriteToolTipSettings() in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.ToolTips.cs:line 194
   at H.NotifyIcon.TaskbarIcon.OnToolTipTextChanged(String oldValue, String newValue) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.ToolTips.cs:line 43
   at H.NotifyIcon.TaskbarIcon.<>c.<.cctor>b__222_5(DependencyObject sender, DependencyPropertyChangedEventArgs args) in /_/src/libs/H.NotifyIcon.Wpf/DependencyPropertyGenerator/H.Generators.DependencyPropertyGenerator/TaskbarIcon.Properties.ToolTipText.generated.cs:line 22
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at MS.Internal.Data.ValueChangedEventManager.ValueChangedRecord.OnValueChanged(Object sender, EventArgs e)
   at DS4WinWPF.DS4Forms.ViewModels.TrayIconViewModel.set_TooltipText(String value)
   at DS4WinWPF.DS4Forms.ViewModels.TrayIconViewModel.PopulateToolText()
   at DS4WinWPF.DS4Forms.ViewModels.TrayIconViewModel.<StartPopulateText>b__59_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at DS4WinWPF.App.Main()
2022-11-15 10:27:16.8842|INFO|Stopping Virtual Output Controllers
2022-11-15 10:27:16.8842|INFO|Closing connection to ViGEmBus
2022-11-15 10:27:16.8842|INFO|Stopping DS4 Input Controllers
2022-11-15 10:27:16.8842|INFO|Stopped DS4Windows
```
