### ISSUE TITLE
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) 

### ISSUE THREAD

**Issue by mpgiii** [Ryochan7/DS4Windows#2635]
**Describe the bug**
Running DS4Windows as a Task on Startup, when I connect a DS4 via Bluetooth, I'm given a backtrace in the logs, DS4Windows consistently uses about 15-30% of my CPU. Window is still responsive, but pressing "Stop" grays the button out and nothing happens. Have to kill the task and restart it for it to work.

**To Reproduce**
1. Have DS4Windows boot on startup
2. Connect PS4 controller by pressing the PS button

**Expected behavior**
self explanatory

**Screenshots and Logs**
All logs seem normal until trying to connect -- when doing so this backtrace spits out
```
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
  at DS4Windows.ControlService.PluginOutDev(Int32 index, DS4Device device)
  at DS4Windows.ControlService.PrepareConnectedInputControllerSettingEvents(Int32 numControllers, DS4Device device, Int32 index)
  at DS4Windows.ControlService.HotPlug()
  at DS4WinWPF.DS4Forms.MainWindow.InnerHotplug2()
  at DS4WinWPF.DS4Forms.MainWindow.<WndProc>b__84_0()
  at System.Threading.Tasks.Task.InnerInvoke()
  at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
  at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
  at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
  --- End of inner exception stack trace ---
```

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro 21H2 (OS build 19044.2130)
 - DS4Windows Version: 3.1.7 (has been happening through many stable releases, didn't make bug report until now)

**Additional context**
Sometimes, killing the process and starting it back up again does not fix anything. In this case, I kill the process, unpair my DS4, re-pair it, and then start back up DS4Windows. Once I do this, it begins working as expected again.

**Comment by Ryochan7** [comment]
Had this happen to myself while testing a new feature out. The failure occurs while trying to create the log message if the virtual device connection fails. The output device will not exist so a NullReferenceException will pop up when attempting to access a device from the reference pointer. Got the issue fixed on my end but I have not added the code to the repo yet.
