### ISSUE TITLE
Silently not launching after update. I suspect something to do with Windows Defender. Any suggestions?

### ISSUE THREAD

**Issue by gitOnThat** [Ryochan7/DS4Windows#2658]
### Discussed in https://github.com/Ryochan7/DS4Windows/discussions/2657

<div type='discussions-op-text'>

<sup>Originally posted by **gitOnThat** October 27, 2022</sup>
Tried reinstalling everything. After a fresh install I get this error on first launch then does nothing on subsequent launch attempts.

2022-10-27 13:30:09.4358|INFO|DS4Windows version 3.1.9
2022-10-27 13:30:09.4358|INFO|DS4Windows exe file: DS4Windows.exe
2022-10-27 13:30:09.4358|INFO|DS4Windows Assembly Architecture: x64
2022-10-27 13:30:09.4358|INFO|OS Version: Microsoft Windows NT 10.0.19043.0
2022-10-27 13:30:09.4358|INFO|OS Product Name: Windows 10 Enterprise
2022-10-27 13:30:09.4358|INFO|OS Release ID: 2009
2022-10-27 13:30:09.4358|INFO|System Architecture: x64
2022-10-27 13:30:09.4358|INFO|Logger created
2022-10-27 13:30:09.4358|INFO|No config found. Creating default config
2022-10-27 13:30:09.4891|INFO|Default config created
2022-10-27 13:30:09.6023|INFO|LinkedProfiles.xml can't be found.
2022-10-27 13:30:10.6713|INFO|Running as Admin
2022-10-27 13:30:10.6713|INFO|HidHide control device found
2022-10-27 13:30:11.6843|WARN|System.AggregateException: One or more errors occurred. (Could not load file or assembly 'Nefarius.ViGEm.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Operation did not complete successfully because the file contains a virus or potentially unwanted software. (0x800700E1))
 ---> System.IO.FileLoadException: Could not load file or assembly 'Nefarius.ViGEm.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Operation did not complete successfully because the file contains a virus or potentially unwanted software. (0x800700E1)
File name: 'Nefarius.ViGEm.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at DS4Windows.ControlService.Start(Boolean showlog)
   at DS4WinWPF.DS4Forms.MainWindow.<>c__DisplayClass26_0.<LateChecks>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
2022-10-27 13:30:45.1931|INFO|Request App Shutdown</div>

**Comment by Masamune3210** [comment]
As I said in the discussion post, your best temp fix is to try whitelisting the folder you have DS4Windows in Windows Security. Defender is incorrectly detecting the vigem client library as malicious and refusing to let the system load it, which causes the program to explode

**Comment by gitOnThat** [comment]
> As I said in the discussion post, your best temp fix is to try whitelisting the folder you have DS4Windows in Windows Security. Defender is incorrectly detecting the vigem client library as malicious and refusing to let the system load it, which causes the program to explode

Thank you! Reinstalling and whitelisting the folder worked.
