### ISSUE TITLE
DS4Windows Battery Indicator Flickering between 90 and 100% and eventual crash via USB

### ISSUE THREAD

**Issue by Gustavo17pacheco** [Ryochan7/DS4Windows#2691]
I'm pretty sure I don't have a genuine controller here, but if there's a way to fix it I'd be thankful. 
Whenever I'm using my controller via USB, which is my preferred way so I don't have to keep re-pairing it to my PC or PS4, it crashes after about x number of minutes, being completely random.

The battery indicator in-app keep changing from 90 to 100% constantly and if I leave the lightbar to indicate charging it flashes like crazy between on or off.
This isn't a USB issue as this cable works just fine on my friend's legitimate controller on this computer and works just fine on the suspect controller via the PS4.

This issue does not happen when playing via bluetooth.

These are my DS4Windows logs

2022-11-14 10:53:05.0252|INFO|DS4Windows version 3.1.10
2022-11-14 10:53:05.0252|INFO|DS4Windows exe file: DS4Windows.exe
2022-11-14 10:53:05.0252|INFO|DS4Windows Assembly Architecture: x64
2022-11-14 10:53:05.0252|INFO|OS Version: Microsoft Windows NT 10.0.22621.0
2022-11-14 10:53:05.0252|INFO|OS Product Name: Windows 10 Pro
2022-11-14 10:53:05.0252|INFO|OS Release ID: 2009
2022-11-14 10:53:05.0252|INFO|System Architecture: x64
2022-11-14 10:53:05.0252|INFO|Logger created
2022-11-14 10:53:05.8148|INFO|Running as User
2022-11-14 10:53:05.8148|INFO|Some applications may block controller inputs. (Windows UAC Conflictions). Please go to https://docs.ds4windows.app/troubleshooting/kb-mouse-issues/#windows-not-responding-to-ds4ws-kb-m-commands-in-some-situations for more information and workarounds.
2022-11-14 10:53:05.8148|INFO|HidHide control device found
2022-11-14 10:53:06.8342|INFO|Starting...
2022-11-14 10:53:06.8342|INFO|Using output KB+M handler: SendInput
2022-11-14 10:53:06.8342|INFO|Connection to ViGEmBus 1.21.442.0 established
2022-11-14 10:53:06.8356|INFO|Searching for controllers...
2022-11-14 10:53:06.8356|INFO|Using Shared Mode
2022-11-14 10:53:06.8802|INFO|Found Controller: 4B:E1:EB:F4:5B:4E (USB) (DS4 v.2).
2022-11-14 10:53:07.2176|INFO|Plugging in virtual X360 controller (XInput slot #1) in output slot #1
2022-11-14 10:53:07.2176|INFO|Associated input controller #1 (DS4 v.2) to virtual X360 Controller in output slot #1
2022-11-14 10:53:07.2416|INFO|Controller 1 is using Profile "Default". Battery level is 90%
2022-11-14 10:58:29.5507|INFO|Disassociated virtual X360 Controller in output slot #1 from input controller #1 (DS4 v.2)
2022-11-14 10:58:29.5507|INFO|Unplugging virtual X360 Controller from output slot #1
2022-11-14 10:58:29.5507|INFO|Controller 1 was removed or lost connection
2022-11-14 10:58:59.1339|INFO|Found Controller: 4B:E1:EB:F4:5B:4E (USB) (DS4 v.2).
2022-11-14 10:58:59.3897|INFO|Plugging in virtual X360 controller (XInput slot #1) in output slot #1
2022-11-14 10:58:59.3897|INFO|Associated input controller #1 (DS4 v.2) to virtual X360 Controller in output slot #1
2022-11-14 10:58:59.3897|INFO|Controller 1 is using Profile "Default". Battery level is 90%
2022-11-14 11:00:26.9529|INFO|Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode=995
2022-11-14 11:00:26.9529|INFO|Disassociated virtual X360 Controller in output slot #1 from input controller #1 (DS4 v.2)
2022-11-14 11:00:26.9529|INFO|Unplugging virtual X360 Controller from output slot #1
2022-11-14 11:00:26.9529|INFO|Controller 1 was removed or lost connection
2022-11-14 11:00:36.5698|INFO|Found Controller: 4B:E1:EB:F4:5B:4E (USB) (DS4 v.2).
2022-11-14 11:00:36.8253|INFO|Plugging in virtual X360 controller (XInput slot #1) in output slot #1
2022-11-14 11:00:36.8253|INFO|Associated input controller #1 (DS4 v.2) to virtual X360 Controller in output slot #1
2022-11-14 11:00:36.8253|INFO|Controller 1 is using Profile "Default". Battery level is 90%
2022-11-14 11:05:39.0425|INFO|Disassociated virtual X360 Controller in output slot #1 from input controller #1 (DS4 v.2)
2022-11-14 11:05:39.0425|INFO|Unplugging virtual X360 Controller from output slot #1
2022-11-14 11:05:39.0425|INFO|Controller 1 was removed or lost connection
2022-11-14 11:05:53.1096|INFO|Found Controller: 4B:E1:EB:F4:5B:4E (USB) (DS4 v.2).
2022-11-14 11:05:53.3710|INFO|Plugging in virtual X360 controller (XInput slot #1) in output slot #1
2022-11-14 11:05:53.3710|INFO|Associated input controller #1 (DS4 v.2) to virtual X360 Controller in output slot #1
2022-11-14 11:05:53.3710|INFO|Controller 1 is using Profile "Default". Battery level is 100%
2022-11-14 11:07:57.6781|ERROR|Thread Crashed with message UpdateToolTip failed.
2022-11-14 11:07:57.6887|ERROR|System.InvalidOperationException: UpdateToolTip failed.
   at H.NotifyIcon.Core.TrayIcon.UpdateToolTip(String text) in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 365
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at MS.Internal.Data.ValueChangedEventManager.ValueChangedRecord.OnValueChanged(Object sender, EventArgs e)
   at DS4WinWPF.DS4Forms.ViewModels.TrayIconViewModel.PopulateToolText()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2022-11-14 11:07:57.6887|ERROR|Thread Crashed with message UpdateToolTip failed.
2022-11-14 11:07:57.6887|ERROR|System.InvalidOperationException: UpdateToolTip failed.
   at H.NotifyIcon.Core.TrayIcon.UpdateToolTip(String text) in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 365
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at MS.Internal.Data.ValueChangedEventManager.ValueChangedRecord.OnValueChanged(Object sender, EventArgs e)
   at DS4WinWPF.DS4Forms.ViewModels.TrayIconViewModel.PopulateToolText()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at DS4WinWPF.App.Main()
2022-11-14 11:07:57.6887|INFO|Stopping Virtual Output Controllers
2022-11-14 11:07:57.6887|INFO|Closing connection to ViGEmBus
2022-11-14 11:07:57.6976|INFO|Disassociated virtual X360 Controller in output slot #1 from input controller #1 (DS4 v.2)
2022-11-14 11:07:57.6976|INFO|Unplugging virtual X360 Controller from output slot #1
2022-11-14 11:07:57.6976|INFO|Controller 1 was removed or lost connection
2022-11-14 11:07:57.7453|INFO|Stopping DS4 Input Controllers
2022-11-14 11:07:57.7453|INFO|Stopped DS4Windows

and I get this on event viewer as well:

`Faulting application name: DS4Windows.exe, version: 3.1.10.0, time stamp: 0x6331eb0e
Faulting module name: KERNELBASE.dll, version: 10.0.22621.755, time stamp: 0x19d26491
Exception code: 0xe0434352
Fault offset: 0x000000000009039c
Faulting process ID: 0x0x3AD8
Faulting application start time: 0x0x1D8F8306B0E6582
Faulting application path: C:\Users\user\Desktop\DS4Windows\DS4Windows.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: f093d234-06c2-4db7-b090-08e6d1938ee5
Faulting package full name: 
Faulting package-relative application ID: `

Any help would be appreciated.

**Comment by Ryochan7** [comment]
Looks like two different issues are at play. Not even going to worry about the device disconnecting issue at this point; no enough information to know what is happening. The crash was being caused by the notify icon raising an exception when attempting to update. That problem should have been resolved several releases ago but I cannot remember which one.
