### ISSUE TITLE
DS4Windows.exe crashes on Win 11 laptop after wake up - Log error: Thread Crashed with message UpdateToolTip failed

### ISSUE THREAD

**Issue by forao** [Ryochan7/DS4Windows#2731]
**Describe the bug**
DS4Windows.exe crashes on a Windows 11 laptop when the computer wakes up. 

**To Reproduce**
1. Install DS4Windows on a computer laptop
2. Put the laptop to sleep
3. Wake the laptop (NOTE: it doesn't always crash on wake up; it happens sometimes. In my case, once every 24 hours. Within this period I may go thru the cycle of sleep/wake computer around 7-8 times)
4. DS4Windows tooltip icon is gone from tray area and application has crashed

**Expected behavior**
DS4Windows is launched and operative after computer is waked from sleep state.

**Screenshots and Logs**
2022-12-12 17:03:43.0727|INFO|DS4Windows version 3.1.11
2022-12-12 17:03:43.0727|INFO|DS4Windows exe file: DS4Windows.exe
2022-12-12 17:03:43.0727|INFO|DS4Windows Assembly Architecture: x64
2022-12-12 17:03:43.0727|INFO|OS Version: Microsoft Windows NT 10.0.22621.0
2022-12-12 17:03:43.0727|INFO|OS Product Name: Windows 10 Pro
2022-12-12 17:03:43.0727|INFO|OS Release ID: 2009
2022-12-12 17:03:43.0727|INFO|System Architecture: x64
2022-12-12 17:03:43.0727|INFO|Logger created
2022-12-12 17:03:43.2705|INFO|LinkedProfiles.xml can't be found.
2022-12-12 17:03:44.9539|INFO|Running as User
2022-12-12 17:03:44.9539|INFO|Some applications may block controller inputs. (Windows UAC Conflictions). Please go to https://docs.ds4windows.app/troubleshooting/kb-mouse-issues/#windows-not-responding-to-ds4ws-kb-m-commands-in-some-situations for more information and workarounds.
2022-12-12 17:03:46.0154|INFO|Starting...
2022-12-12 17:03:46.0154|INFO|Using output KB+M handler: SendInput
2022-12-12 17:03:46.0154|INFO|Connection to ViGEmBus 1.21.442.0 established
2022-12-12 17:03:46.0154|INFO|Searching for controllers...
2022-12-12 17:03:46.0154|INFO|Using Shared Mode
2022-12-12 17:06:41.1492|INFO|Stopping Virtual Output Controllers
2022-12-12 17:06:41.1492|INFO|Closing connection to ViGEmBus
2022-12-12 17:06:41.1492|INFO|Stopping DS4 Input Controllers
2022-12-12 17:06:41.1492|INFO|Stopped DS4Windows
2022-12-12 17:51:04.3266|INFO|Starting...
2022-12-12 17:51:04.3266|INFO|Using output KB+M handler: SendInput
2022-12-12 17:51:04.3266|INFO|Connection to ViGEmBus 1.21.442.0 established
2022-12-12 17:51:04.3266|INFO|Searching for controllers...
2022-12-12 17:51:04.3266|INFO|Using Shared Mode
2022-12-12 17:51:04.3621|ERROR|Thread Crashed with message UpdateToolTip failed.
2022-12-12 17:51:04.4922|ERROR|System.InvalidOperationException: UpdateToolTip failed.
   at H.NotifyIcon.Core.TrayIcon.UpdateToolTip(String text) in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 365
   at H.NotifyIcon.TaskbarIcon.WriteToolTipSettings() in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.ToolTips.cs:line 194
   at H.NotifyIcon.TaskbarIcon.OnToolTipTextChanged(String oldValue, String newValue) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.ToolTips.cs:line 43
   at H.NotifyIcon.TaskbarIcon.<>c.<.cctor>b__222_5(DependencyObject sender, DependencyPropertyChangedEventArgs args) in /_/src/libs/H.NotifyIcon.Wpf/DependencyPropertyGenerator/H.Generators.DependencyPropertyGenerator/TaskbarIcon.Properties.ToolTipText.generated.cs:line 22
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.ScheduleTransfer(Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at MS.Internal.Data.PropertyPathWorker.OnValueChanged(Object sender, ValueChangedEventArgs e)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.Windows.WeakEventManager.DeliverEventToList(Object sender, EventArgs args, ListenerList list)
   at MS.Internal.Data.ValueChangedEventManager.ValueChangedRecord.OnValueChanged(Object sender, EventArgs e)
   at DS4WinWPF.DS4Forms.ViewModels.TrayIconViewModel.set_TooltipText(String value)
   at DS4WinWPF.DS4Forms.ViewModels.TrayIconViewModel.PopulateToolText()
   at DS4WinWPF.DS4Forms.ViewModels.TrayIconViewModel.<StartPopulateText>b__59_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 11 22H2
 - DS4Windows Version 3.1.11

**Comment by forao** [comment]
Sorry, just found this issue: #2623 

In this thread, the user @Kubusky mentions in the comments this same error is happening when waking up from sleep. Although the issue OP mentions that it happens while playing games, @Kubusky mentions the same behavior as described on this issue.

Question is: should this issue be closed and continued in #2623?
