### ISSUE TITLE
Not able to connect to UDPServer System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'hostNameOrAddress')

### ISSUE THREAD

**Issue by oliveira666** [Ryochan7/DS4Windows#2776]
Trying to tick the UDP Server box results in this error on the log channel, cant connect a controller after, only when UDP Server is unticked, tried with version 3.2.3 and 3.2.4

01/11/2023 16:00:02: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'hostNameOrAddress'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'hostNameOrAddress')
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress, AddressFamily family)
   at DS4Windows.UdpServer.Start(Int32 port, String listenAddress)
   at DS4Windows.ControlService.Start(Boolean showlog)
   at DS4WinWPF.DS4Forms.MainWindow.<>c__DisplayClass26_0.<LateChecks>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

**Comment by legoshi899** [comment]
Am also experiencing the same issue I thought it was my PC thanks for your reply. your doing a great job keep it up

**Comment by oliveira666** [comment]
Tried it today and its working perfectly as of version 3.2.5, thanks for the fast response, keep up with the great job!
