### ISSUE TITLE
DS4Windows 3.2.9 shutdowns after detecting PS5 Controller

### ISSUE THREAD

**Issue by zombiemaker** [Ryochan7/DS4Windows#2886]
**Describe the bug**
Running version 3.2.9 of PS4Windows on Windows 11.  When DS4Windows starts, it shows that it detected the PS5 controller connected via USB.  It then shutdown with the following error two messages posted in Windows Event Viewer.

Application: DS4Windows.exe
CoreCLR Version: 6.0.1523.11507
.NET Version: 6.0.15
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at DS4Windows.Mouse.sixaxisMoved(DS4SixAxis sender, SixAxisEventArgs arg)
   at DS4Windows.DS4SixAxis.handleSixaxis(Byte* gyro, Byte* accel, DS4State state, Double elapsedDelta)
   at DS4Windows.InputDevices.DualSenseDevice.ReadInput()
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()

Another event message

Faulting application name: DS4Windows.exe, version: 3.2.9.0, time stamp: 0x63cf74d2
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1413, time stamp: 0x5129184b
Exception code: 0xe0434352
Fault offset: 0x000000000008fe7c
Faulting process id: 0x0x2CA4
Faulting application start time: 0x0x1D95F81B6B6B234
Faulting application path: E:\user-data\nick.nguyen\Desktop\DS4Windows\DS4Windows.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: d9a78fea-a9f5-4aa7-908a-261899896b7e
Faulting package full name: 
Faulting package-relative application ID: 

**To Reproduce**
1. PS5 controller disconnected
2. Start PS4Windows
3. Plug in PS5 controller
4. Sound beeps (indicating detection of DualSense)
5. App shows DualSense listed in Controllers tab
6. App then shows empty list in Controllers tab
7. App shutdown

**Expected behavior**
App should just show the DualSense controller connected

**Screenshots and Logs**
See attached images that show the controller connected and the app log.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony PS5 Model CFI-ZCT1W
 - OS: Windows 11 Pro Version 22H2 Build 22621.1413
 - DS4Windows Version 3.2.9

**Additional context**
Add any other contex

![clip-2](https://user-images.githubusercontent.com/8773975/227750585-9b09ccc7-4918-4a5e-aac8-c887eef85e78.png)
t about the problem here.
![clip-1](https://user-images.githubusercontent.com/8773975/227750580-6a96d865-80f3-46e2-89b1-d4f034ea4bb1.png)

**Comment by VorgonBattlecruiser** [comment]
Same thing happens to all three of my V2 DS4 with a double-capacity PAXO battery.

**Comment by Ryochan7** [comment]
Going to need the profile in question to diagnose this further. I would think that some profile group class was not generated that the sixAxisMoved method expects to exist. Everything works fine on my end.
