### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by DAOWAce** [Ryochan7/DS4Windows#481]
Just upgraded from 1.4.116.

Program crashed upon trying to exit.

```
************** Exception Text **************
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()
   at System.Windows.Forms.Application.ExitInternal()
   at System.Windows.Forms.Application.Exit(CancelEventArgs e)
   at DS4Windows.DS4Form.ScpForm_Closing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at DS4Windows.DS4Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
DS4Windows
    Assembly Version: 1.5.15.0
    Win32 Version: 1.5.15
    CodeBase: file:///C:/Users/Owner/Desktop/Castlevania%204/Tools/DS4Windows/DS4Windows.exe
----------------------------------------
Microsoft.Win32.TaskScheduler
    Assembly Version: 2.8.0.0
    Win32 Version: 2.8.0.0
    CodeBase: file:///C:/Users/Owner/Desktop/Castlevania%204/Tools/DS4Windows/Microsoft.Win32.TaskScheduler.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
```

Subsequent launches seemed to require 2 exits to actually exit, but didn't critically error the few times I tested it.

Just reverted back to 1.4.116 to be safe anyway, as I was testing a jitter issue with analog sticks. (DS4 seems to have very poor analog sticks)

**Comment by mika-n** [comment]
This crash seem to happen if you have any of the DS4Win forms open when you try to quit the DS4Win application (either via system tray "exit" menu command or force kill via TaskManager). 

Close all DS4Win windows before closing the application via systemTray icon.

**Comment by Ryochan7** [comment]
This issue has been discussed before. The fix is easy but .NET does not
like it for some reason. Performance of the app would be worse so the fix
was not implemented. You have to make sure that the profile editor is not
still open when you quit DS4Windows.

I guess I can try to test some code changes again and see if I have better
luck.

**Comment by Ryochan7** [comment]
The only compromise that will work is to just close the options form in that circumstance; the more complete routines that I tried did not work out. That means you would have to click the close button twice in that situation. The window size will change upon clicking the window close button the first time. My advice would be to not leave the Profile Editor form open when not editing a profile to remove unneeded overhead.
