### ISSUE TITLE
Rare crashes while using UDP server with Cemu

### ISSUE THREAD

**Issue by Corrodias** [Ryochan7/DS4Windows#602]
I've been getting DS4Windows crashes occasionally. They happen hours apart, so it'd be hard to casually test to see whether something's fixed, but after a couple of days, I could be reasonably certain.

I'm still using Windows 7 x64.

Each crash emits 2 events in the log:
```
Application: DS4Windows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(System.Net.Sockets.Socket)
   at System.Net.Sockets.Socket.SendToAsync(System.Net.Sockets.SocketAsyncEventArgs)
   at DS4Windows.UdpServer.NewReportIncoming(DS4Windows.DualShockPadMeta ByRef, DS4Windows.DS4State)
   at DS4Windows.ControlService+<>c__DisplayClass39_1.<HotPlug>b__3(DS4Windows.DS4Device, System.EventArgs)
   at DS4Windows.DS4Device+ReportHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(DS4Windows.DS4Device, System.__Canon)
   at DS4Windows.DS4Device.performDs4Input()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

```
Faulting application name: DS4Windows.exe, version: 1.6.13.0, time stamp: 0x5c83efbc
Faulting module name: KERNELBASE.dll, version: 6.1.7601.24214, time stamp: 0x5b627415
Exception code: 0xe0434352
Fault offset: 0x000000000001a06d
Faulting process id: 0x1218
Faulting application start time: 0x01d4d6edcc54a53c
Faulting application path: C:\Programs (permissive)\DS4Windows\DS4Windows.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 39a253df-4308-11e9-9bec-000272c6b32d
```

The error looks similar to this, resolved issue: https://github.com/Ryochan7/DS4Windows/issues/454

**Comment by Ryochan7** [comment]
It seems that error would occur if a SocketAsyncEventArgs instance is still being used when SendToAsync is called. The main safe option would be increasing the size of the object pool. On my system, I am lucky if Cemu renders Breath of the Wild at 20 FPS but I have not run into this kind of problem.

**Comment by Corrodias** [comment]
Could Cemu crashing affect this in any way? It does that, occasionally. Regardless, I will of course report back on the result after the next release.

**Comment by Ryochan7** [comment]
I don't think that Cemu crashing would matter in this case. That data from the pool should not be in use after a crash so it should hopefully be safe to write new data to the instance and send it out.

**Comment by Corrodias** [comment]
Played for a little while after that and didn't have more crashes. I'm now using an adapter that handles the BT communication because it's a lot more reliable than Windows is at doing so, so I won't be able to comment on BT stability any more, so I'm closing this.
