### ISSUE TITLE
DS4windows refusing to boot

### ISSUE THREAD

**Issue by arterisk8** [Ryochan7/DS4Windows#925]
DS4windows refusing to boot, opens up to "Program Data" or "AppData" folder choice, no matter what I pick the window closes as normal and then nothing happens thereafter. Have checked the AppData and Program Data" folders after selecting them and there is no reference to DS4windows in either.

This is really frustrating.

**Comment by mika-n** [comment]
What version of DS4Windows you have? The latest V1.7.24?
https://github.com/Ryochan7/DS4Windows/releases

You could try the upcoming new version of the "WPF" build of DS4Windows also. At some point this will replace the current official DS4Windows app.
https://github.com/Ryochan7/DS4Windows/issues/824#issuecomment-565227645

Make sure you have installed all required pre-requisites. DS4Windows app doesn't try to install requierd VisualC++ or .NET Framework runtime libraries, so you have to do it. If you have these requirements then DS4Windows app does try to install a missing VigEm driver, but there has been cases where this automatic installation has failed because of permissions issues. To workaround that potential problem then please download the latest version of Vigem driver ViGEmBus_Setup_1.16.115.exe manually and install it before launching DS4Windows app (see the link list).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-

**Comment by arterisk8** [comment]
Fairly sure I've done all that before but I will do it all again tomorrow
to be sure.

**Comment by arterisk8** [comment]
Tried all of the above, none of it worked. However, the WPF version of DS4
did appear under hidden icons on the taskbar, before disappearing again,
presumably a crash.

**Comment by mika-n** [comment]
Probably both the DS4Windows and the new DS4WindowsWPF crash because of the same problem. The WPF version should dump a logfile messages from an unexpected aborts. Do you see any files in "%APPPATH%\DS4Windows\Logs" folder?

**Comment by Ryochan7** [comment]
One likely reason is that the Windows Management Instrumentation (WMI) service is disabled. That is a standard service for Windows that runs by default. This version of DS4Windows uses WMI to catch suspend and resume events from the system. The older Jays2Kings build attempted to use WMI to check if ScpVBus was installed from sometimes outdated cache data.

No fallback behavior has ever been introduced as, each time I have tried, changes would lead to application slowdown across the board. Maybe I should give it a shot again using the WPF code base as that project has been much more lenient regarding making code changes.

**Comment by arterisk8** [comment]
@mika-n 2019-12-16 20:06:23.9607|INFO|DS4Windows version 1.9.0
2019-12-16 20:06:23.9697|INFO|Logger created
2019-12-16 20:06:25.2950|INFO|App Crashed with message Invalid class 
2019-12-16 20:06:25.2950|ERROR|   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementEventWatcher.Start()
   at DS4WinWPF.DS4Forms.MainWindow..ctor(ArgumentParser parser)
   at DS4WinWPF.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

this is in the logs folder in a notepad file.

**Comment by mika-n** [comment]
@Ryochan7  was on the right track, System.Management.ManagementException is thrown from WMI services. 
https://docs.microsoft.com/en-us/dotnet/api/system.management?view=netframework-4.8

There has been couple cases where WinOS installation had problems with WMI services (disabled or somehow corrupted settings).
https://github.com/Ryochan7/DS4Windows/issues/723#issuecomment-500175421
https://github.com/Ryochan7/DS4Windows/issues/550#issuecomment-455720755

Some users have simply started the "Windows Management Service" OS service (services.msc) or run WinOS repair to fix some weird bugs/corrupted sysreg settings in Windows to restore WMI functionality.

**Comment by Ryochan7** [comment]
I have tested it and the program crashed from a COMException error when ManagementEventWatcher attempts to connect to WMI. I have found a simple fix to work around that issue which runs before the ManagementEventWatcher is initialized. No play testing has been done yet and that is the critical factor.

**Comment by henriquel1997** [comment]
Hi i got the latest version (2.0.0) and also have the same issue. What should i do exactly to fix this?
I tried restarting WMI as explained here but it didn't work: https://docs.microsoft.com/en-us/windows/win32/wmisdk/starting-and-stopping-the-wmi-service .
Also here's the log i got (Classe inválida means Invalid Class btw):

2019-12-26 23:46:47.6253|INFO|DS4Windows version 2.0.0
2019-12-26 23:46:47.6253|INFO|Logger created
2019-12-26 23:46:47.6253|INFO|No config found. Creating default config
2019-12-26 23:46:47.6722|INFO|Default config created
2019-12-26 23:46:48.6059|ERROR|App Crashed with message Classe inválida 
2019-12-26 23:46:48.6059|ERROR|System.Management.ManagementException: Classe inválida 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementEventWatcher.Start()
   at DS4WinWPF.DS4Forms.MainWindow..ctor(ArgumentParser parser)
   at DS4WinWPF.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by henriquel1997** [comment]
Is there any way for me to try and see if the changes you made on that commit fixes this issue?

**Comment by Ryochan7** [comment]
The changes are in version 2.0.1. Hopefully that version works fine on your machine.

**Comment by henriquel1997** [comment]
The new version was able to boot and i got to the screen which tells be to install ViGEmBus!
The problem is that after DS4Windows downloads, it fails to install. But i guess that's not really related to this issue anymore right?
I tried to download ViGEmBus seperately but it also isn't working so i replied to an open issue on their repository.
Anyway, thanks for the help!
